# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# Url to box has been packaged on local
# use Python simple sesrver to share box file
# python -m SimpleHTTPServer 9300

SHARED_BOX_URL = "~/asoft/vagrantbox/precise64.box"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # You should add the following to /etc/hosts
  # gladiolus.local   192.168.33.10

  #config.vm.network :private_network, ip: "192.168.33.10"
  config.vm.network :forwarded_port, guest: 8000, host: 8000
  config.vm.network :forwarded_port, guest: 3306, host: 3306
  config.vm.network :forwarded_port, guest: 8080, host: 8080

  # forwarded port for postgres
  config.vm.network :forwarded_port, guest: 5432, host: 5432

  # Data folder
  config.vm.synced_folder "../../gcloud", "/gcloud"

  if defined?(SHARED_BOX_URL)
    config.vm.box = "gcloud"
    config.vm.box_url = SHARED_BOX_URL
    config.vm.provision "shell", :path => "bootstrap.sh", :privileged => false
  else
    config.vm.box = "gcloud"
    config.vm.box_url = "http://files.vagrantup.com/precise64.box"
    config.vm.provision "shell", :path => "bootstrap.sh", :privileged => false
  end

  config.vm.provider :virtualbox do |vb|
    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end
end